### ISSUE TITLE
How to reset transform css after the dragging stops?

### ISSUE THREAD

**Issue by levelingup** [STRML/react-draggable#608]
I want to reset the overwritten transform that it adds when you drag an element. The reason I'm doing this is because I've captured the position of top/left css with percentages when dragging, but because it adds the transform still, the position gets offset from where I stop the drag.

**Comment by levelingup** [comment]
I found that all I needed to do was set position to 0

`<Draggable position={{x: 0, y: 0}}></Draggable>`

**Comment by vibonacci** [comment]
Took me a while as well to realize what the position prop was actually meant for.

**Comment by Melkeydev** [comment]
@levelingup Hey can you explain this? I am having a tough time to reset the position after transform. I am use a global state management and I set initial `defaultPosition` values to the component. I cannot figure out how to get back to the original position. 
When I add position to 0 like you suggested, the component does not move. After drag it right away snaps to the 0,0 co-ordinate, but what I want is the ability to move and reset it to how the element was originally before any transform took place
