### ISSUE TITLE
React Draggable not working on Mobile 

### ISSUE THREAD

**Issue by Rugved1652** [STRML/react-draggable#642]
I am not able to drag component on mobile browsers

**Comment by udilbar** [comment]
Same issue on me too

**Comment by Rugved1652** [comment]
hey I solved the problem and forget to close issue... In my case it was happening because of onClick() event in parent div .. 

use onTouchStart event for mobile devices like this
onClick={(e) => handleSomething(e)}
onTouchStart={(e) => handleSomething(e)}

**Comment by varsha-M-I** [comment]
can you please give example
