### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property

### ISSUE THREAD

**Issue by rortan134** [STRML/react-draggable#643]
I'm currently getting this error when trying to use the Draggable component

`'Draggable' cannot be used as a JSX component.
  Its instance type 'Draggable' is not a valid JSX element.
    Type 'Draggable' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.`

![image](https://user-images.githubusercontent.com/37253958/158056259-0c9b90c8-82ba-47d6-9aaf-be315437afb7.png)

Removing every prop from the component still gives an error.
I've tried reinstalling the package twice and it's at it latest version, ^4.4.4.

**Comment by ncheungg** [comment]
experiencing this as well on `^4.4.5`. tried restarting vscode, reinstall the package, but haven't found a fix to this bug. the code compiles fine

(TS2607)
