### ISSUE TITLE
Incompatible with @types/react v18.x due to removal of children from FC and Component types

### ISSUE THREAD

**Issue by ashmortar** [STRML/react-draggable#647]
If you update [@types/react](https://www.npmjs.com/package/@types/react) to version 18 it introduces a breaking change that makes `<DraggableCore/>` fail typescript compilation.  This is due to the [removal of implicit children](https://solverfox.dev/writing/no-implicit-children/) from FC and Component.

>  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DraggableCore> & Pick<Readonly<Partial<DraggableCoreProps>>, never> & Partial<...> & Partial<...>'.ts(2769)

**Comment by sseemmiin** [comment]
same as me

**Comment by samyan** [comment]
same here

**Comment by mahdi-farnia** [comment]
same

**Comment by STRML** [comment]
Fixed in `4.4.5`
