### ISSUE TITLE
Overlap Draggables

### ISSUE THREAD

**Issue by BryceBlankinship** [STRML/react-draggable#650]
I use the normal Draggable element on "Cards" in my project, and the user can create new cards and delete them, however when a new card is created, it spawns below the last generated card. This in itself is not a problem, I actually prefer the functionality of this, however when a card gets deleted, all of the Draggables shift up a position and if enough cards get generated and then deleted, some cards will fly up and go out of view for the user, lost forever unless I intervene with sending a delete request to the REST api containing all the Draggable's positions. My workaround for now was to add a top boundary, so that cards hit a "ceiling" when one gets deleted, but the whole mechanic of the cards shifting up a position whenever one is deleted is pretty annoying for the UX. Is this a CSS issue? Cards can overlap once they've spawned in, but they won't spawn in overlapped. I have a feeling this is more a problem with CSS but if anyone has encountered this before please let me know. I can provide a video of what I'm talking about if this was confusing to read.

**Comment by miestr** [comment]
The trick that worked for me is applying css position: 'relative' to the parent element (the one containing the draggables) and adding css position: 'absolute' to the draggable's css class "handle". Then the elements are positioned exactly where you define the initialPosition and they overlap if needed.

**Comment by BryceBlankinship** [comment]
This worked. Thank you for figuring this out. I knew it was CSS related but wasn't about to attempt hundreds of CSS changes aiming in the dark.
