### ISSUE TITLE
(0 , _clsx2.default) is not a function

### ISSUE THREAD

**Issue by gsiwiec01** [STRML/react-draggable#667]
Hi,
few days ago I updated all the packages in my project. Unfortunately, I came across an error in this repository. At first, I thought it might be the children's fault, but no. I hope you can get it right :)

![image](https://user-images.githubusercontent.com/13869373/177617526-8f096fc3-bad2-41b1-a186-21d268df8892.png)

**Comment by anudeepreddy** [comment]
Hi @gsiwiec01 ,

How were you able to fix this issue?
