### ISSUE TITLE
`bounds` doesn't work as expected

### ISSUE THREAD

**Issue by TechStudent10** [STRML/react-draggable#695]
When setting `bounds` to `"parent"` or the selector of the parent element, I can only move up and down in that parent element.

`<Draggable>` component (wrapped in another component):

```jsx
function ComponentContainer(props: any) {
    const nodeRef = useRef(null) as RefObject<HTMLDivElement>

    return <Draggable nodeRef={nodeRef} {...props}>
        <div ref={nodeRef}>{props.children}</div>
    </Draggable>
}

export default function Preview(props: PreviewProps) {
    console.log(props.elements)

    const previewRef = useRef() as RefObject<HTMLDivElement>

    return <div className={`preview ${props.type}`} ref={previewRef}>
        {props.elements && Object.keys(props.elements).map((element_index) => {
            let element: ProjectElement = props.elements[element_index]
            let Component = element.render
            return <ComponentContainer
                onDrag={(e: any, data: any) => console.log(data)}
                bounds={`.preview`}
            >
                <Component />
            </ComponentContainer>
        })}
    </div>
}
```

**Comment by cwaj400** [comment]
Hi! Please could you create a Codebox.io? I believe I am facing the same issue and want to establish if so: www.codesandbox.io
Thank you,

**Comment by TechStudent10** [comment]
> Hi! Please could you create a Codebox.io? I believe I am facing the same issue and want to establish if so: [www.codesandbox.io](http://www.codesandbox.io) Thank you,

Sorry, but I've switched to another library and that one is working "fine" for now. The lib is `@neodrag/react`.

**Comment by cwaj400** [comment]
No problem. Please close this issue.
Thanks,
