### ISSUE TITLE
Fix React 18 Concurrent Mode drag glitches

### ISSUE THREAD

**Issue by erictheswift** [STRML/react-draggable#698]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-draggable@4.4.5` for the project I'm working on.

In React 18 concurrent mode setState updates gets batched by default. That means they never run synchronously — always deferred.

I've faced an issue when drag parameters got out of sync after React 18 update on slow machine.
Visual manifestation were:

https://user-images.githubusercontent.com/2434839/212761083-648aca50-0b14-403b-82ad-2a778ebdc3d4.mov

items were dragged more far away than the cursor moved when CPU was throttled / occupied.

My investigation brought me to setState that is used for in-between drag events state and that `this.state` can and returns stale (old) values until rerender occurs in React 18.

As this state is not used inside render() function and updates do not need to trigger rerender, being motivated to make minimal change that would work for me and likely not break anything,

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-draggable/build/cjs/DraggableCore.js b/node_modules/react-draggable/build/cjs/DraggableCore.js
index 07b05f1..d9ea373 100644
--- a/node_modules/react-draggable/build/cjs/DraggableCore.js
+++ b/node_modules/react-draggable/build/cjs/DraggableCore.js
@@ -175,12 +175,7 @@ var DraggableCore = /*#__PURE__*/function (_React$Component) {
       // touchpoint was set to this element.
 
       var touchIdentifier = (0, _domFns.getTouchIdentifier)(e);
-
-      _this.setState({
-        touchIdentifier: touchIdentifier
-      }); // Get the current drag point from the event. This is used as the offset.
-
-
+      this.state.touchIdentifier = touchIdentifier; // Get the current drag point from the event. This is used as the offset.
       var position = (0, _positionFns.getControlPosition)(e, touchIdentifier, _assertThisInitialized(_this));
       if (position == null) return; // not possible but satisfies flow
 
@@ -201,11 +196,9 @@ var DraggableCore = /*#__PURE__*/function (_React$Component) {
       // so we know how much we've moved during the drag. This allows us
       // to drag elements around even if they have been moved, without issue.
 
-      _this.setState({
-        dragging: true,
-        lastX: x,
-        lastY: y
-      }); // Add events to the document directly so we catch when the user's mouse/touch moves outside of
+      _this.state.dragging = true;
+      _this.state.lastX = x;
+      _this.state.lastY = y; // Add events to the document directly so we catch when the user's mouse/touch moves outside of
       // this element. We use different events depending on whether or not we have detected that this
       // is a touch-capable device.
 
@@ -262,10 +255,8 @@ var DraggableCore = /*#__PURE__*/function (_React$Component) {
         return;
       }
 
-      _this.setState({
-        lastX: x,
-        lastY: y
-      });
+      _this.state.lastX = x
+      _this.state.lastY = y
     });
 
     _defineProperty(_assertThisInitialized(_this), "handleDragStop", function (e) {
@@ -303,11 +294,9 @@ var DraggableCore = /*#__PURE__*/function (_React$Component) {

**Comment by maxwellwalin** [comment]
Thank you for this!! Just resolved the same issue I was having.

**Comment by knownasilya** [comment]
We noticed that with this fix the deltaX and x values jump back and fourth like 23, 22, 23, 22, 21, 22, 20, etc... which makes the drag incorrect (disconnects from speed of the cursor as the user drags and feels slow). Reverting to v4.4.5 fixes the issue in React 18 for us. Using Draggable in controlled mode.
