### ISSUE TITLE
Resize css and react-resizable is not working with react-draggable

### ISSUE THREAD

**Issue by Ajamuar** [STRML/react-draggable#702]
I tried using the css property `resize` as well as tried using react-draggable. In both cases, the element got dragged instead of being resized. I would really appreciate some help regarding this.

Examples:
https://codesandbox.io/s/interesting-noyce-5vvikc?file=/src/App.js
https://codesandbox.io/s/fervent-cerf-0z335q?file=/src/components/Line.tsx

**Comment by Oceanestars** [comment]
Hey @Ajamuar ! You can totally use both, but you'd want to separate the two. So like an area to drag and an area to resize.
A super quick example with your code. Here I can drag with just h1 and resize the whole thing still :)
```
import "./styles.css";
import Draggable from "react-draggable";

export default function App() {
  return (
    <Draggable handle="#draggable-h1" cancel={".react-resizable-handle"}>
      <div className="App">
        <h1 id="draggable-h1">Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
      </div>
    </Draggable>
  );
}


```

**Comment by Ajamuar** [comment]
Thanks a lot for this @Oceanestars! This worked perfectly!
