### ISSUE TITLE
react-draggable@4.4.6: exports is not defined

### ISSUE THREAD

**Issue by lqomg** [STRML/react-draggable#734]
react-draggable@4.4.6 After packaging under Linux, there is an error that exports is not defined. 
There is no problem with the 4.4.5 version.

node: 16.14.2

**Comment by lijiweigh** [comment]
I have the same issue

**Comment by OneHatRepo** [comment]
Same here. I had to downgrade to 4.4.5

**Comment by lqomg** [comment]
配置babel，targets中chrome 为 90

**Comment by OneHatRepo** [comment]
I don't understand. How can I use 4.4.6?

**Comment by tihuan** [comment]
Just wanted to confirm that a year later 4.4.6 is still having problem with `exports is not defined` and had to downgrade to 4.4.5 to get it to work
